name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xmx3G -XX:+UseG1GC
  JVM_OPTS: -XX:+PrintCommandLineFlags -Xmx3G -XX:+UseG1GC

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ['master']
  release:
    types:
      - published

jobs:
  lint:

    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v14
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Lint code
        run: sbt check

  mdoc:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v14
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Check Document Generation
        run: sbt docs/mdoc

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java: ['adopt@1.8', 'adopt@1.11']
        scala: ['2.12.16', '2.13.8', '3.4.3']
        platform: ['JVM', 'JS']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Mima Check
        if: ${{ matrix.platform == 'JVM' }}
        run: sbt ++${{ matrix.scala }}! mimaCheck
      - name: Test
        run: sbt ++${{ matrix.scala }}! test${{ matrix.platform }}

  ci:
    runs-on: ubuntu-latest
    needs: [lint, mdoc, test]
    steps:
      - name: Run all steps
        run:
            echo "ci passed, github.ref ${{ github.ref }}"

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [ci]
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v14
      - name: Release
        run: sbt ci-release
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}